<?php
/*
@ccnRef: @theme_pafco/layout
*/

defined('MOODLE_INTERNAL') || die();
$templatecontext = [
    'lang_menu' =>  $langMenu,
    'sitename' => format_string($SITE->shortname, true, ['context' => context_course::instance(SITEID), "escape" => false]),
    'output' => $OUTPUT,
    'ccnLogoUrl' => $ccnLogoUrl,
    'pageheading' => format_text($pageheading, FORMAT_HTML, array('filter' => true)),
    'sidepreblocks' => $blockshtml,
    'ccn_login' => $_ccnlogin,
    // 'ccn_registration' => $_ccnregistration,
    'ccn_activitynav' => $_ccnCourseSectionNav,
    'ccn_course_url' => $ccnCourseUrl,
    'ccn_dashboard_url' => $CFG->wwwroot . '/my',
    'ccn_globalsearch' => $_ccnglobalsearch,
    'ccn_globalsearch_navbar' => $_ccnglobalsearch_navbar,
    'ccn_librarylist' => $_ccnlibrarylist,
    'library_list_blocks' => $OUTPUT->blocks('library-list'),
    'has_library_list_blocks' => strpos($OUTPUT->blocks('library-list'), 'data-block=') !== false,
    'navbar_blocks' => $OUTPUT->blocks('navbar'),
    'has_navbar_blocks' => strpos($OUTPUT->blocks('navbar'), 'data-block=') !== false,
    'leftblocks' => $leftblocks,
    'hasblocks' => $hasblocks,
    'hasleftblocks' => $hasleftblocks,
    'hassideblocks' => $hassideblocks,
    'sidebar_single' => $sidebar_single,
    'sidebar_single_left' => $sidebar_single_left,
    'sidebar_single_right' => $sidebar_single_right,
    'sidebar_left' => $sidebar_left,
    'sidebar_right' => $sidebar_right,
    'sidebar_double' => $sidebar_double,
    'sidebar_none' => $sidebar_none,
    'participant_user_profile' => $userProfileFromCourseParticipants,
    'bodyattributes' => $bodyattributes,
    'headerlogo1' => $headerlogo1,
    'headerlogo2' => $headerlogo2,
    'headerlogo3' => $headerlogo3,
    'headerlogo4' => $headerlogo4,
    'headerlogo_mobile' => $headerlogo_mobile,
    'footerlogo1' => $footerlogo1,
    'heading_bg' => $heading_bg,
    'favicon' => $favicon,
    'regionmainsettingsmenu' => $regionmainsettingsmenu,
    'hasregionmainsettingsmenu' => !empty($regionmainsettingsmenu),
    'loginblocks' => $loginblocks,
    'hasloginblocks' => !empty($loginblocks),
    'searchblocks' => $searchblocks,
    'hassearchblocks' => !empty($searchblocks),
    'blocks_user_notifications' => $blocks_user_notifications,
    'blocks_user_messages' => $blocks_user_messages,
    'blocks_fullwidth_top' => $blocks_fullwidth_top,
    'blocks_fullwidth_bottom' => $blocks_fullwidth_bottom,
    'blocks_above_content' => $blocks_above_content,
    'has_blocks_above_content' => !empty($blocks_above_content),
    'blocks_below_content' => $blocks_below_content,
    'has_blocks_below_content' => !empty($blocks_below_content),
    'has_blocks_fullwidth_top' => !empty($blocks_fullwidth_top),
    'has_blocks_fullwidth_bottom' => !empty($blocks_fullwidth_bottom),
    'is_course' => $PAGE->bodyid == 'page-course-view-topics' || $PAGE->bodyid == 'page-course-view-tiles',
    'is_blog' => $PAGE->bodyid == 'page-blog-index',
    'is_frontpage' => $PAGE->bodyid == 'page-site-index',
    'courseid' => $courseid,
    'coursefullname' => $coursefullname,
    'courseshortname' => $courseshortname,
    'coursecategory' => $coursecategory,
    'coursesummary' => $coursesummary,
    'courseformat' => $courseformat,
    'coursecreated' => $coursecreated,
    'coursemodified' => $coursemodified,
    'coursestartdate' => $coursestartdate,
    'courseenddate' => $courseenddate,
    'numberofusers' => $numberofusers,
    'pafco_facebook_url' => format_text(get_config('theme_pafco', 'pafco_facebook_url'), FORMAT_HTML, array('filter' => true)),
    'pafco_twitter_url' => format_text(get_config('theme_pafco', 'pafco_twitter_url'), FORMAT_HTML, array('filter' => true)),
    'pafco_instagram_url' => format_text(get_config('theme_pafco', 'pafco_instagram_url'), FORMAT_HTML, array('filter' => true)),
    'pafco_pinterest_url' => format_text(get_config('theme_pafco', 'pafco_pinterest_url'), FORMAT_HTML, array('filter' => true)),
    'pafco_dribbble_url' => format_text(get_config('theme_pafco', 'pafco_dribbble_url'), FORMAT_HTML, array('filter' => true)),
    'pafco_google_url' => format_text(get_config('theme_pafco', 'pafco_google_url'), FORMAT_HTML, array('filter' => true)),
    'pafco_youtube_url' => format_text(get_config('theme_pafco', 'pafco_youtube_url'), FORMAT_HTML, array('filter' => true)),
    'pafco_vk_url' => format_text(get_config('theme_pafco', 'pafco_vk_url'), FORMAT_HTML, array('filter' => true)),
    'pafco_500px_url' => format_text(get_config('theme_pafco', 'pafco_500px_url'), FORMAT_HTML, array('filter' => true)),
    'pafco_behance_url' => format_text(get_config('theme_pafco', 'pafco_behance_url'), FORMAT_HTML, array('filter' => true)),
    'pafco_digg_url' => format_text(get_config('theme_pafco', 'pafco_digg_url'), FORMAT_HTML, array('filter' => true)),
    'pafco_flickr_url' => format_text(get_config('theme_pafco', 'pafco_flickr_url'), FORMAT_HTML, array('filter' => true)),
    'pafco_foursquare_url' => format_text(get_config('theme_pafco', 'pafco_foursquare_url'), FORMAT_HTML, array('filter' => true)),
    'pafco_linkedin_url' => format_text(get_config('theme_pafco', 'pafco_linkedin_url'), FORMAT_HTML, array('filter' => true)),
    'pafco_medium_url' => format_text(get_config('theme_pafco', 'pafco_medium_url'), FORMAT_HTML, array('filter' => true)),
    'pafco_meetup_url' => format_text(get_config('theme_pafco', 'pafco_meetup_url'), FORMAT_HTML, array('filter' => true)),
    'pafco_snapchat_url' => format_text(get_config('theme_pafco', 'pafco_snapchat_url'), FORMAT_HTML, array('filter' => true)),
    'pafco_tumblr_url' => format_text(get_config('theme_pafco', 'pafco_tumblr_url'), FORMAT_HTML, array('filter' => true)),
    'pafco_vimeo_url' => format_text(get_config('theme_pafco', 'pafco_vimeo_url'), FORMAT_HTML, array('filter' => true)),
    'pafco_wechat_url' => format_text(get_config('theme_pafco', 'pafco_wechat_url'), FORMAT_HTML, array('filter' => true)),
    'pafco_whatsapp_url' => format_text(get_config('theme_pafco', 'pafco_whatsapp_url'), FORMAT_HTML, array('filter' => true)),
    'pafco_wordpress_url' => format_text(get_config('theme_pafco', 'pafco_wordpress_url'), FORMAT_HTML, array('filter' => true)),
    'pafco_weibo_url' => format_text(get_config('theme_pafco', 'pafco_weibo_url'), FORMAT_HTML, array('filter' => true)),
    'pafco_telegram_url' => format_text(get_config('theme_pafco', 'pafco_telegram_url'), FORMAT_HTML, array('filter' => true)),
    'pafco_moodle_url' => format_text(get_config('theme_pafco', 'pafco_moodle_url'), FORMAT_HTML, array('filter' => true)),
    'pafco_amazon_url' => format_text(get_config('theme_pafco', 'pafco_amazon_url'), FORMAT_HTML, array('filter' => true)),
    'pafco_slideshare_url' => format_text(get_config('theme_pafco', 'pafco_slideshare_url'), FORMAT_HTML, array('filter' => true)),
    'pafco_soundcloud_url' => format_text(get_config('theme_pafco', 'pafco_soundcloud_url'), FORMAT_HTML, array('filter' => true)),
    'pafco_leanpub_url' => format_text(get_config('theme_pafco', 'pafco_leanpub_url'), FORMAT_HTML, array('filter' => true)),
    'pafco_xing_url' => format_text(get_config('theme_pafco', 'pafco_xing_url'), FORMAT_HTML, array('filter' => true)),
    'pafco_bitcoin_url' => format_text(get_config('theme_pafco', 'pafco_bitcoin_url'), FORMAT_HTML, array('filter' => true)),
    'pafco_twitch_url' => format_text(get_config('theme_pafco', 'pafco_twitch_url'), FORMAT_HTML, array('filter' => true)),
    'pafco_github_url' => format_text(get_config('theme_pafco', 'pafco_github_url'), FORMAT_HTML, array('filter' => true)),
    'pafco_gitlab_url' => format_text(get_config('theme_pafco', 'pafco_gitlab_url'), FORMAT_HTML, array('filter' => true)),
    'pafco_forumbee_url' => format_text(get_config('theme_pafco', 'pafco_forumbee_url'), FORMAT_HTML, array('filter' => true)),
    'pafco_trello_url' => format_text(get_config('theme_pafco', 'pafco_trello_url'), FORMAT_HTML, array('filter' => true)),
    'pafco_weixin_url' => format_text(get_config('theme_pafco', 'pafco_weixin_url'), FORMAT_HTML, array('filter' => true)),
    'pafco_slack_url' => format_text(get_config('theme_pafco', 'pafco_slack_url'), FORMAT_HTML, array('filter' => true)),
    'pafco_copyright' => format_text(get_config('theme_pafco', 'pafco_copyright'), FORMAT_HTML, array('filter' => true)),
    'footer_col_1_title' => format_text(get_config('theme_pafco', 'footer_col_1_title'), FORMAT_HTML, array('filter' => true)),
    'footer_col_1_body' => format_text(get_config('theme_pafco', 'footer_col_1_body'), FORMAT_HTML, array('filter' => true, 'noclean' => true)),
    'footer_col_2_title' => format_text(get_config('theme_pafco', 'footer_col_2_title'), FORMAT_HTML, array('filter' => true)),
    'footer_col_2_body' => format_text(get_config('theme_pafco', 'footer_col_2_body'), FORMAT_HTML, array('filter' => true, 'noclean' => true)),
    'footer_col_3_title' => format_text(get_config('theme_pafco', 'footer_col_3_title'), FORMAT_HTML, array('filter' => true)),
    'footer_col_3_body' => format_text(get_config('theme_pafco', 'footer_col_3_body'), FORMAT_HTML, array('filter' => true, 'noclean' => true)),
    'footer_col_4_title' => format_text(get_config('theme_pafco', 'footer_col_4_title'), FORMAT_HTML, array('filter' => true)),
    'footer_col_4_body' => format_text(get_config('theme_pafco', 'footer_col_4_body'), FORMAT_HTML, array('filter' => true, 'noclean' => true)),
    'footer_col_5_title' => format_text(get_config('theme_pafco', 'footer_col_5_title'), FORMAT_HTML, array('filter' => true)),
    'footer_col_5_body' => format_text(get_config('theme_pafco', 'footer_col_5_body'), FORMAT_HTML, array('filter' => true, 'noclean' => true)),
    'footer_menu' => format_text(get_config('theme_pafco', 'footer_menu'), FORMAT_HTML, array('filter' => true)),
    'footer_column_1' => $footer_column_1,
    'footer_column_2' => $footer_column_2,
    'footer_column_3' => $footer_column_3,
    'footer_column_4' => $footer_column_4,
    'footer_column_5' => $footer_column_5,
    'footer_col_1_class' => $footer_col_1_class,
    'footer_col_2_class' => $footer_col_2_class,
    'footer_col_3_class' => $footer_col_3_class,
    'footer_col_4_class' => $footer_col_4_class,
    'footer_col_5_class' => $footer_col_5_class,
    'cta_text' => format_text(get_config('theme_pafco', 'cta_text'), FORMAT_HTML, array('filter' => true)),
    'cta_link' => format_text(get_config('theme_pafco', 'cta_link'), FORMAT_HTML, array('filter' => true)),
    'cta_icon' => ($ccnIcon = get_config('theme_pafco', 'cta_icon_ccn_icon_class')) ? $ccnIcon : 'flaticon-megaphone',
    'email_address' => format_text(get_config('theme_pafco', 'email_address'), FORMAT_HTML, array('filter' => true)),
    'phone' => format_text(get_config('theme_pafco', 'phone'), FORMAT_HTML, array('filter' => true)),
    'custom_css' => $custom_css,
    'custom_css_dashboard' => $custom_css_dashboard,
    'custom_js' => $custom_js,
    'custom_js_dashboard' => $custom_js_dashboard,
    'display_library_list' => $display_library_list,
    'logotype' => $logotype,
    'logo_image' => $logo_image,
    'logo' => $logo,
    'logotype_footer' => $logotype_footer,
    'logo_image_footer' => $logo_image_footer,
    'logo_footer' => $logo_footer,
    'user_profile_picture' => new moodle_url('/user/pix.php/'.$USER->id.'/f1.jpg'),
    'profile_icon_username' => $ccnProfileIconUsername,
    'user_username' => $USER->username,
    'user_firstname' => $USER->firstname,
    'user_lastname' => $USER->lastname,
    'user_email' => $USER->email,
    'user_language' => $USER->lang,
    'user_id' => $USER->id,
    'isloggedin' => $isloggedin == 'TRUE',
    'notloggedin' => $isloggedin == 'FALSE',
    'signup_is_enabled' => $signup_is_enabled == true,
    'signup_is_disabled' => $signup_is_enabled == false,
    'header_1' => $headertype == 1,
    'header_2' => $headertype == 2,
    'header_3' => $headertype == 3,
    'header_4' => $headertype == 4,
    'header_5' => $headertype == 5,
    'header_6' => $headertype == 6,
    'header_7' => $headertype == 7,
    'header_8' => $headertype == 8,
    'header_9' => $headertype == 9,
    'header_10' => $headertype == 10,
    'header_11' => $headertype == 11,
    'header_12' => $headertype == 12,
    'header_13' => $headertype == 13,
    'header_14' => $headertype == 14,
    'footer_1' => $footertype == 1,
    'footer_2' => $footertype == 2,
    'footer_3' => $footertype == 3,
    'footer_4' => $footertype == 4,
    'footer_5' => $footertype == 5,
    'footer_6' => $footertype == 6,
    'footer_7' => $footertype == 7,
    'footer_8' => $footertype == 8,
    'footer_9' => $footertype == 9,
    'breadcrumb_default' => $breadcrumb_style == 0,
    'breadcrumb_m' => $breadcrumb_style == 1,
    'breadcrumb_s' => $breadcrumb_style == 2,
    'breadcrumb_xs' => $breadcrumb_style == 3,
    'breadcrumb_hidden' => $breadcrumb_style == 4,
    'breadcrumb_classes' => $breadcrumb_classes,
    'breadcrumb_clip_dash' => $breadcrumb_clip_dash,
    'preloader_load' => $preloader_duration == 0,
    'preloader_ready' => $preloader_duration == 1,
    'preloader_5' => $preloader_duration == 2,
    'preloader_4' => $preloader_duration == 3,
    'preloader_3' => $preloader_duration == 4,
    'preloader_2' => $preloader_duration == 5,
    'preloader_disable' => $preloader_duration == 6,
    'headertype_frontpage_only' => FALSE,
    'headertype_all_pages' => TRUE,
    'header_search_icon' => $header_search == 0,
    'header_search_bar' => $header_search == 1,
    'header_login_popup' => $header_login == 0,
    'header_login_link' => $header_login == 1,
    'back_to_top' => $back_to_top == 0,
    // 'dashboard_sticky_header' => $dashboard_sticky_header == 0,
    'logo_styles' => $logo_styles,
    'logo_styles_footer' => $logo_styles_footer,
    'gmaps_key' => get_config('theme_pafco', 'gmaps_key'),
    'messages_link' => $messages_link,
    'profile_link' => $profile_link,
    'preferences_link' => $preferences_link,
    'grades_link' => $grades_link,
    'dash_header_white' => get_config('theme_pafco', 'dashboard_header') == 1,
    'dash_tabs' => $dash_tablet_count != 0,
    'dash_tab_col_class' => $dash_tab_col_class,
    'dash_tablet_1' => $dash_tablet_1,
    'dash_tablet_1_title' => format_text($dash_tablet_1_title, FORMAT_HTML, array('filter' => true)),
    'dash_tablet_1_subtitle' => format_text($dash_tablet_1_subtitle, FORMAT_HTML, array('filter' => true)),
    'dash_tablet_1_link' => $dash_tablet_1_link,
    'dash_tablet_1_icon' => $dash_tablet_1_icon,
    'dash_tablet_2' => $dash_tablet_2,
    'dash_tablet_2_title' => format_text($dash_tablet_2_title, FORMAT_HTML, array('filter' => true)),
    'dash_tablet_2_subtitle' => format_text($dash_tablet_2_subtitle, FORMAT_HTML, array('filter' => true)),
    'dash_tablet_2_link' => $dash_tablet_2_link,
    'dash_tablet_2_icon' => $dash_tablet_2_icon,
    'dash_tablet_3' => $dash_tablet_3,
    'dash_tablet_3_title' => format_text($dash_tablet_3_title, FORMAT_HTML, array('filter' => true)),
    'dash_tablet_3_subtitle' => format_text($dash_tablet_3_subtitle, FORMAT_HTML, array('filter' => true)),
    'dash_tablet_3_link' => $dash_tablet_3_link,
    'dash_tablet_3_icon' => $dash_tablet_3_icon,
    'dash_tablet_4' => $dash_tablet_4,
    'dash_tablet_4_title' => format_text($dash_tablet_4_title, FORMAT_HTML, array('filter' => true)),
    'dash_tablet_4_subtitle' => format_text($dash_tablet_4_subtitle, FORMAT_HTML, array('filter' => true)),
    'dash_tablet_4_link' => $dash_tablet_4_link,
    'dash_tablet_4_icon' => $dash_tablet_4_icon,
    'display_course_content' => $display_course_content == 1,
    'incourse_layout_dashboard' => $incourse_layout_dashboard == 1,
    'disable_stricky_dashboard' => $dashboard_scroll_header == 1,
    'dashboard_scroll_drawer' => $dashboard_scroll_drawer == 1,
    // 'dashboard_drawer_navigation' => $dashboard_left_drawer != (1 || 2),
    'dashboard_nav_user' => $dashboard_left_drawer != (1 || 2 || 3) /* Theme Setting equals '0' */,
    'dashboard_nav_flat' => $dashboard_left_drawer == 3,
    'disable_dashboard_drawer' => $dashboard_left_drawer == 2 || ($dashboard_left_drawer == 1 && !$sidebar_left),
    'incourse' => $incourse == 1,
    'in_course_activity'=>$inCourseActivity,
    'show_course_start' => $showCourseStartDate != 1,
    'show_course_category' => $showCourseCategory != 1,
    // 'user_profile_layout_dashboard' => $user_profile_layout_dashboard == 1,
    'social_target_href' => $social_target_href,
    'if_user_navigation_icon' => get_config('theme_pafco', 'navigation_icon_visibility') != 1,
    'if_user_notification_icon' => get_config('theme_pafco', 'notification_icon_visibility') != 1,
    'if_user_messages_icon' => get_config('theme_pafco', 'messages_icon_visibility') != 1,
    'if_user_dark_mode_icon' => get_config('theme_pafco', 'dark_mode_icon_visibility') != 1,
    'user_navigation_icon' => 'flaticon-settings',
    'user_notification_icon' => 'flaticon-alarm',
    'user_messages_icon' => 'flaticon-speech-bubble',
    'user_dark_mode_icon' => 'ccn-flaticon-hide',
    'show_settings_controls' => $ccn_page_settings_controls == 1,
    'if_breadcrumb_title' => get_config('theme_pafco', 'breadcrumb_title') != 1,
    'if_breadcrumb_trail' => get_config('theme_pafco', 'breadcrumb_trail') != 1,
    'pafco_focus_sidebar' => !empty(get_config('theme_pafco', 'pafco_focus_sidebar')) && get_config('theme_pafco', 'pafco_focus_sidebar') === '1' ? false : true,
    'lang_menu_icons' => !empty(get_config('theme_pafco', 'language_menu')) && get_config('theme_pafco', 'language_menu') === '1' ? false : true,
    'is_4' => (int)$ccnMdlVersion >= 400 ? true : false
];

if((int)$ccnMdlVersion >= 400) {
  $templatecontext['primarymoremenu'] = $primarymenu['moremenu'];
  $templatecontext['secondarymoremenu'] = $secondarynavigation ? : false;
  $templatecontext['eithermoremenu'] = !empty($primarymenu['moremenu']) || $secondarynavigation ? true : false;
  $templatecontext['mobileprimarynav'] = $primarymenu['mobileprimarynav'];
  $templatecontext['headercontent'] = $headercontent;
  $templatecontext['overflow'] = $overflow;
  $templatecontext['addblockbutton'] = $addblockbutton ?? null;
  // 'primarymoremenu' => $primarymenu['moremenu'],
  // 'secondarymoremenu' => $secondarynavigation ? : false,
  // 'eithermoremenu' => !empty($primarymenu['moremenu']) || $secondarynavigation ? true : false,
  // 'mobileprimarynav' => $primarymenu['mobileprimarynav'],
  // 'headercontent' => $headercontent,
  // 'overflow' => $overflow,
  // 'addblockbutton' => $addblockbutton,
}


// var_dump($primarymenu['moremenu']);
$PAGE->requires->jquery();
$ccnLcVbCollection = array(
  "pafco_about_1",
  "pafco_about_2",
  "pafco_accordion",
  "pafco_action_panels",
  "pafco_boxes",
  "pafco_blog_recent_slider",
  "pafco_faqs",
  "pafco_event_list",
  "pafco_event_list_2",
  "pafco_featured_teacher",
  "pafco_featured_posts",
  "pafco_featured_video",
  "pafco_features",
  "pafco_gallery_video",
  "pafco_parallax",
  "pafco_parallax_apps",
  "pafco_parallax_counters",
  "pafco_parallax_features",
  "pafco_parallax_testimonials",
  "pafco_parallax_subscribe",
  "pafco_parallax_subscribe_2",
  "pafco_partners",
  "pafco_parallax_white",
  "pafco_pills",
  "pafco_price_tables",
  "pafco_price_tables_dark",
  "pafco_services",
  "pafco_services_dark",
  "pafco_simple_counters",
  "pafco_hero_1",
  "pafco_hero_2",
  "pafco_hero_3",
  "pafco_hero_4",
  "pafco_hero_5",
  "pafco_hero_6",
  "pafco_hero_7",
  "pafco_slider_1",
  "pafco_slider_1_v",
  "pafco_slider_2",
  "pafco_slider_3",
  "pafco_slider_4",
  "pafco_slider_5",
  "pafco_slider_6",
  "pafco_slider_7",
  "pafco_slider_8",
  "pafco_steps",
  "pafco_steps_dark",
  "pafco_subscribe",
  "pafco_tablets",
  "pafco_tabs",
  "pafco_tstmnls",
  "pafco_tstmnls_2",
  "pafco_tstmnls_3",
  "pafco_tstmnls_4",
  "pafco_tstmnls_5",
  "pafco_tstmnls_6",
  "pafco_contact_form",
  "pafco_course_categories",
  "pafco_course_categories_2",
  "pafco_course_categories_3",
  "pafco_course_categories_4",
  "pafco_course_categories_5",
  "pafco_course_overview",
  "pafco_course_instructor",
  "pafco_course_rating",
  "pafco_course_grid",
  "pafco_course_grid_2",
  "pafco_course_grid_3",
  "pafco_course_grid_4",
  "pafco_course_grid_5",
  "pafco_course_grid_6",
  "pafco_course_grid_7",
  "pafco_course_grid_8",
  "pafco_featuredcourses",
  "pafco_courses_slider",
  "pafco_more_courses",
  "pafco_users_slider",
  "pafco_users_slider_2",
  "pafco_users_slider_2_dark",
  "pafco_users_slider_round",
 );
$ccnControlBlockListUri = $CFG->wwwroot . '/theme/pafco/ccn/visualize/ccn_block/jpeg/large/';
$ccnControlBlockListUriThumb = $CFG->wwwroot . '/theme/pafco/ccn/visualize/ccn_block/jpeg/thumb/';
$PAGE->requires->js_init_call('ccnCommentHandler', array(get_string('add_comment', 'theme_pafco')));
$PAGE->requires->js_init_call('ccnControl', array($ccnControlBlockListUri, $ccnControlBlockListUriThumb, $ccnLcVbCollection, $ccnMdlVersion));
$nav = $PAGE->flatnav;

foreach ($nav->getIterator() as &$item) {
    if ($item->type == \navigation_node::TYPE_COURSE
        || $item->type == \navigation_node::TYPE_SECTION
        || $item->key === 'home'
    ) {
        $nav->remove($item->key);
    }
    if (in_array($item->key ,
        ['participants', 'badgesview', 'competencies','addblock', 'grades','privatefiles','mycourses','contentbank'])){
        $nav->remove($item->key);
    }
}


$templatecontext['flatnavigation'] = $nav;
$templatecontext['firstcollectionlabel'] = $nav->get_collectionlabel();

//$nav = $PAGE->primarynav;
//$templatecontext['flatnavigation'] = $nav;
//$templatecontext['firstcollectionlabel'] = $nav->children->get_collectionlabel();

if($PAGE->pagetype == "admin-setting-themesettingpafco") {
  $PAGE->requires->css('/theme/pafco/style/pafco.editor.theme.css');
  $PAGE->requires->js('/theme/pafco/javascript/pafco.editor.theme.js', true);
}
